CREATE TABLE IF NOT EXISTS usuarios (
    uuid UUID PRIMARY KEY,
    gender VARCHAR(20),
    title VARCHAR(20),
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    email VARCHAR(255),
    username VARCHAR(100),
    phone VARCHAR(50),
    cell VARCHAR(50),
    id_type VARCHAR(50),
    id_value VARCHAR(50),
    dob_date DATE,
    age INT,
    street_number VARCHAR(50),
    street_name VARCHAR(255),
    city VARCHAR(100),
    state VARCHAR(100),
    country VARCHAR(100),
    postcode VARCHAR(20),
    latitude NUMERIC(10, 6),
    longitude NUMERIC(10, 6),
    nat VARCHAR(10),
    picture_large TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);