services:
  postgresql-data:
    image: postgres:16
    container_name: data-db
    environment:
      POSTGRES_DB: ${APP_POSTGRES_DB:-postgres_db}
      POSTGRES_USER: ${APP_POSTGRES_USER:-myuser}
      POSTGRES_PASSWORD: ${APP_POSTGRES_PASSWORD:-mypassword}
    volumes:
      - postgres_data_app:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "7200:5432"
    networks:
      - red-interna

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: my_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-adminpassword}
    ports:
      - "7300:80"
    depends_on:
      - postgresql-data
    networks:
      - red-interna
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  data-lake:
    image: minio/minio
    container_name: data-lake
    command: server /data --console-address ":9001"
    ports:
      - "7400:9000"
      - "7401:9001"
    volumes:
      - data-lake:/data
    environment:
      - MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minio}
      - MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minio123}
    restart: always
    networks:
      - red-interna

volumes:
  postgres_data_app:
  data-lake:
  pgadmin_data:

networks:
  red-interna:
    external: true
